#!/bin/bash
                                                                                                                               
java -Xms1g -Xmx1g  -cp "target/classes/" diningRoom.DiningTable
